// import Image from "next/image"
// import { Inter } from "@next/font/google"
import Head from "next/head"
import Header from "@/components/Header"
import Hero from "@/components/Hero"
import About from "@/components/About"
import WorkExperience from "@/components/WorkExperience"
import Contact from "@/components/Contact"
import Projects from "@/components/Projects"
import Skills from "@/components/Skills"
export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen  overflow-auto z-0  snap-mandatory">
      <Head>
        <title>KhemRaj Fekar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section id="hero" className="snap-start mt-15 md:mt-5">
        <Hero />
      </section>
      <section id="about" className="snap-center">
        <About />
      </section>
      {/* Experience */}
      <section id="experience">
        <WorkExperience />
      </section>
      {/* Skills */}
      <section id="skills">
        <Skills />
      </section>
      {/* Projects */}
      <section id="projects">
        <Projects />
      </section>
      {/* Contact Me */}
      <section id="contact">
        <Contact />
      </section>
    </div>
  )
}
